const sheetDS = {
  millimeters: 7,
  tenthToMm: 0.1807975,
  divisions: 2,
  pageLayout: {
    pageHeight: 1545,
    pageWidth: 1194,
    leftMargin: 70,
    rightMargin: 70,
    topMargin: 88,
    bottomMargin: 88,
  },
  parts: {},
  partElements: [
    {
      scoreMap: {
        1: [
          {
            name: "note",
            voice: 1,
            type: "quarter",
            stem: -1,
            xmlDuration: "2",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "4",
            divisions: 2,
            keys: ["C/5"],
            isLastNote: false,
            measureNumber: 1,
            isFirstNote: true,
            divPoint: 0,
          },
          {
            name: "note",
            voice: 1,
            type: "quarter",
            stem: -1,
            xmlDuration: "2",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "4",
            divisions: 2,
            keys: ["C/5"],
            isLastNote: false,
            measureNumber: 1,
            divPoint: 2,
          },
          {
            name: "note",
            voice: 1,
            type: "quarter",
            stem: -1,
            xmlDuration: "2",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "4",
            divisions: 2,
            keys: ["C/5"],
            isLastNote: false,
            measureNumber: 1,
            divPoint: 4,
          },
          {
            name: "note",
            voice: 1,
            type: "eighth",
            stem: -1,
            beam: {
              name: "beam",
              attrs: {
                number: "1",
              },
              text: "begin",
            },
            xmlDuration: "1",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "8",
            divisions: 1,
            keys: ["C/5"],
            isLastNote: false,
            measureNumber: 1,
            divPoint: 6,
          },
          {
            name: "note",
            voice: 1,
            type: "eighth",
            stem: -1,
            beam: {
              name: "beam",
              attrs: {
                number: "1",
              },
              text: "end",
            },
            xmlDuration: "1",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "8",
            divisions: 1,
            keys: ["C/5"],
            isLastNote: true,
            measureNumber: 1,
            divPoint: 7,
          },
        ],
        2: [
          {
            name: "note",
            voice: 1,
            type: "eighth",
            stem: -1,
            beam: {
              name: "beam",
              attrs: {
                number: "1",
              },
              text: "begin",
            },
            xmlDuration: "1",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "8",
            divisions: 1,
            keys: ["C/5"],
            isLastNote: false,
            measureNumber: 2,
            isFirstNote: true,
            divPoint: 8,
          },
          {
            name: "note",
            voice: 1,
            type: "eighth",
            stem: -1,
            beam: {
              name: "beam",
              attrs: {
                number: "1",
              },
              text: "end",
            },
            xmlDuration: "1",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "8",
            divisions: 1,
            keys: ["C/5"],
            isLastNote: false,
            measureNumber: 2,
            divPoint: 9,
          },
          {
            name: "note",
            voice: 1,
            type: "eighth",
            stem: -1,
            beam: {
              name: "beam",
              attrs: {
                number: "1",
              },
              text: "begin",
            },
            xmlDuration: "1",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "8",
            divisions: 1,
            keys: ["C/5"],
            isLastNote: false,
            measureNumber: 2,
            divPoint: 10,
          },
          {
            name: "note",
            voice: 1,
            type: "eighth",
            stem: -1,
            beam: {
              name: "beam",
              attrs: {
                number: "1",
              },
              text: "end",
            },
            xmlDuration: "1",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "8",
            divisions: 1,
            keys: ["C/5"],
            isLastNote: false,
            measureNumber: 2,
            divPoint: 11,
          },
          {
            name: "note",
            voice: 1,
            type: "quarter",
            stem: -1,
            xmlDuration: "2",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "4",
            divisions: 2,
            keys: ["C/5"],
            isLastNote: false,
            measureNumber: 2,
            divPoint: 12,
          },
          {
            name: "note",
            voice: 1,
            type: "quarter",
            stem: -1,
            xmlDuration: "2",
            pitch: {
              key: "C",
              octave: "5",
            },
            pitchKey: "C5",
            duration: "4",
            divisions: 2,
            keys: ["C/5"],
            isLastNote: true,
            measureNumber: 2,
            divPoint: 14,
          },
        ],
      },
    },
  ],
};

export default sheetDS;
